version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hermes
    ports:
      - "8090:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    depends_on:
      - mysql
      - redis
    restart: always
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: myStrongP@ssw0rd
    ports:
      - "3306:3306"
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
