version: "3.9"

services:
    #################### mysql ####################
    mysql:
        ports:
            - ${LOCAL_DB_PORT:-}:${DB_PORT:-3306}

    #################### redis ####################
    redis:
        ports:
            - ${LOCAL_REDIS_PORT:-}:${REDIS_PORT:-6379}

    ################### rabbitmq ##################
    rabbitmq:
        ports:
            - ${LOCAL_RABBIT_PORT:-}:${RABBIT_PORT:-5672}
            - ${RABBIT_MANAGEMENT:-}:${RABBIT_MANAGEMENT:-15672}
